name = "open-learning-cloud-worker"
main = "src/index.js"
compatibility_date = "2023-12-01"

[env.production]
name = "open-learning-cloud-worker"
route = "https://media.open-learning-cloud.dev/*"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "open-learning-media"

[[kv_namespaces]]
binding = "METADATA_KV"
id = "your-kv-namespace-id"

[triggers]
crons = ["0 2 * * *"]

[vars]
FIREBASE_PROJECT_ID = "open-learning-cloud"
